### ISSUE TITLE
I can send HTMLCOIN to myself

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#14]
@senagbe 

Steps to reproduce:
- Open the app
- Login
- Open the Wallet page
- Tap and hold on your displayed address - address will be copied
- Tap on the Send tab
- Add Your copied address
- Add value and send
- The payment will be accepted and placed
- Go back to the Wallet page
- Unconfirmed transaction is displayed there
- After some time it will be confirmed and it was possible to send HTMLCOIN to myself - this should not happen.

The issue is present on iOS and on Android as well!

![senttomyself-1](https://user-images.githubusercontent.com/4669689/36489488-76812f98-1726-11e8-86dd-879a5765a14b.PNG)
![senttomyself-2](https://user-images.githubusercontent.com/4669689/36489490-76a1fe76-1726-11e8-8528-3272c1f83bc2.PNG)
![senttomyself-3](https://user-images.githubusercontent.com/4669689/36489491-76c30300-1726-11e8-871b-087f5503a751.PNG)

**Comment by senagbe** [comment]
@vsabolc I don't think this is an issue.
