### ISSUE TITLE
Android: Incorrect Passphrase was not declined, but a new account was created

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#30]
@senagbe 

Steps:
- Start the latest app
- Tap on the IMPORT WALLET
- Enter a totally random text - make sure it is not a valid passphrase
- Tap on the IMPORT button when it become active
- The Create PIN page appear

This is not correct - as there was added a totally incorrect passphrase, so error message should appear and not the Create new user flow should be followed!

**Comment by dohaivu** [comment]
in Bitcoinj: passphrase is invalid if it's not 12 words.
System don't know and don't care the content of it
Only the user who enters know it's correct for his wallet or not.

The system code will concatenate them into a string, use it as a password to generate binary seeds, then creating private key, public key and addresses.

If user enters invalid words, system will generate wrong keys and wrong addresses for him

**Comment by vsabolc** [comment]
Tested. The system allows 12 words. Closing.
