### ISSUE TITLE
Android: App Crash On Next Startup

### ISSUE THREAD

**Issue by STewieH** [HTMLCOIN/htmlcoin-android#38]
Android Nougat 7.0.0
Samsung Galaxy S7 Edge Vanilla

Try and open the app again after a prolonged period of not being opened from the menu and the app will crash.

(Very randomly happens)
Open App and use it
Switch to others apps and continue using them for prolonged periods
Tap HTMLCoin Wallet in menu to open app
App will crash and not run

Tombstone attached with bugreport.
https://www.dropbox.com/s/7vnsfu572st5r66/bugreport-2018-03-07-08-12-55.zip?dl=0

**Comment by vsabolc** [comment]
The only thing what I noticed is the crash with the PIN. The app all by itself does not crashes at my side.

**Comment by vsabolc** [comment]
Tested. The same issue does not appear.
