### ISSUE TITLE
Android: Navigating to the Wallet screen is showing for a very short period the two dots from the Activity screen

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#40]
@senagbe

Steps to reproduce:
- Open the Android app
- Log in
- Go to any screen except the Wallet screen (Profile, News, Send)
- Navigate to the Wallet screen
- Over the bottom menu (Wallet, Profile, News, Send) the two dots, the navigation option from the Activity, will be visible for a very short period

This is visible only with the light theme and not visible on the dark theme

**Comment by longpham2310** [comment]
@vsabolc It is fixed.

**Comment by vsabolc** [comment]
Tested. It is fixed.
