### ISSUE TITLE
Android: Some thick lines are visible on the Profile page

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#45]
@senagbe

Steps to reproduce:
- Open the latest app
- Login
- Open the Profile page
- Change the Theme to the dark
- Check the Profile page
- There are some thick lines visible under Language and TouchID options - the others are normal delimiter lines.

![profilesscreen](https://user-images.githubusercontent.com/4669689/37158254-3b82177e-22eb-11e8-8f23-0fbf453ace54.png)

**Comment by longpham2310** [comment]
@vsabolc The dark theme is implementing. I will assign back to you when it has done.

**Comment by vsabolc** [comment]
Leaving in the Testing column and will be retested after the Dark theme implementation is done.

**Comment by dohaivu** [comment]
It's implemented

**Comment by vsabolc** [comment]
Tested. It is fixed.
