### ISSUE TITLE
Android - Dark Theme: About page does not have the HTMLCOIN page displayed like the light theme About page

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#46]
@senagbe 

Steps to reproduce:
- Open the app
- Login
- Open the Profile page
- Make sure using the Light theme
- Open the About page
- It has the correct logo and the correct app name
- Go back and switch the theme to dark
- Open again the About page
- It has the QTUM logo and HTMLCOIN app name

![android-dark](https://user-images.githubusercontent.com/4669689/37158713-54223b50-22ec-11e8-9114-73f0d10daac7.png)
![android-light](https://user-images.githubusercontent.com/4669689/37158714-544230c2-22ec-11e8-8dc4-5fb1d4e8ad58.png)

**Comment by dohaivu** [comment]
dark theme is not ready to test yet
It's in progress

**Comment by vsabolc** [comment]
Tested. It is fixed.
