### ISSUE TITLE
Android: IMPORTANT - After the screen lock, I was able to operate in the app without PIN code

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#55]
@senagbe

Steps to reproduce:
- Open the Android app in Samsung S7 (7.0)
- Log in
- Send/Receive several Transaction
- View different screen
- Open notifications
- Lock the screen
- Use the phone again
- Now, the PIN code should be asked, but I can just open the application
- The PIN code is not required
- Restart the app
- The PIN code will be required again
- I was not managed to reproduce the same behavior on Sony Xperia X (8.0)

Also tried to reproduce it again on Samsung S7, but after app restart it worked fine. Will do more testing around on this maybe can find the reason why this happened.

**Comment by vsabolc** [comment]
The issue is device specific for sure because it occurs a lot. One more scenario is when the login is blocked for 10 mins. If this issue occurs (yes, it occurred even in that state) by the time when the Login should be blocked 10 min, the user will be able without login to operate with the app.

**Comment by senagbe** [comment]
@longpham2310 we will need to test this specifically on the S7

**Comment by longpham2310** [comment]
I was tested. It's a bug in handle notification flow. We will fix it.

**Comment by vsabolc** [comment]
Tested. It is fixed.
