### ISSUE TITLE
Support QR Codes without labels

### ISSUE THREAD

**Issue by senagbe** [HTMLCOIN/htmlcoin-android#58]
Android exhibits the same issue with QR codes which do not contain labels as seen in https://github.com/HTMLCOIN/htmlcoin-ios/issues/37 from @lunamonkey the details of which were found by various members of internal test as well as @dohaivu during dev testing. It's amrked as an enhancement as it appears to have been by design or omission on the part of the QTum guys.

**Comment by longpham2310** [comment]
@senagbe I checked it for the Android version. It doesn't happen. It only happens on the iOS version (HTMLCOIN/htmlcoin-ios#37).
- I also checked the Android code. It doesn't require labels.

**Comment by lunamonkey** [comment]
Is it possible another field is throwing the error? Message or Amount? 

The testers were reporting Bleutrade QRs as failing on Android.

**Comment by senagbe** [comment]
@longpham2310 can you support raw addresses please.

**Comment by longpham2310** [comment]
@senagbe I did it.

**Comment by vsabolc** [comment]
@senagbe I have tested it and it looks ok. Can be closed.
