### ISSUE TITLE
The keyboard is still displayed after the PIN number is entered and the Send verification is done

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#62]
@senagbe 

Steps to reproduce:
- Open the latest Android app
- Open the Send page
- Add Address and add value
- Tap on the Send button
- PIN confirmation popup will appear
- The Keyboard will be displayed as well
- Enter PIN and it will be verified
- Transaction successful popup will appear
- Tap on OK
- The empty SEND page will stay displayed together with the keyboard - this looks bad hides a big part of the screen and makes the navigation hard
- After the PIN was verified, hide the keyboard

![keyboard-afterpopupclosed](https://user-images.githubusercontent.com/4669689/37293654-3c873268-2614-11e8-8620-a6278bb0ae16.png)
![keyboardunderthepoup](https://user-images.githubusercontent.com/4669689/37293655-3cab8c1c-2614-11e8-8c25-4adc3c965df6.png)

**Comment by dohaivu** [comment]
It's fixed

**Comment by vsabolc** [comment]
Tested. It is fixed.
