### ISSUE TITLE
Android 8: The device does not receive push notifications about the Transfers

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#63]
@senagbe 

Made the testing on an old phone Samsung S4 - Android 5.0.1 and on Android 8.0 (Sony Xperia X)

The Android 8.0 device does not receive push notifications at all if the application is running.

The Android 5.0.1 device does receive push notifications even if the app is running!

The behavior should be the same on all Android versions.

**Comment by senagbe** [comment]
@vsabolc can you clarify please? 

> The Android 5.0.1 device does receive push notifications even if the app is running!
?

**Comment by vsabolc** [comment]
@senagbe Yes, the Samsung S4 (Android 5.0.1) received the notification even if the app was on the screen - the notification appeared at top in the task bar for sent and for approved transaction as well!

**Comment by longpham2310** [comment]
@senagbe It should behave the push notification during the app launch. Because If we don't show it. The user doesn't know there is a new transaction event coming. 
- Let me investigate why the push doesn't show up on Android 8.

**Comment by vsabolc** [comment]
It is working ok now. Closing.
