### ISSUE TITLE
Android: The debug build does not allow to take screenshot

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#8]
@senagbe 

Steps to reproduce:
- Install the debug build of the app
- Login
- Try to take screenshot of the app
- Error message appear and it is not possible to take screenshot
- App was installed on Sony Xperia X - Android 7.1.1

**Comment by senagbe** [comment]
@vsabolc I have removed the debug download link as it isn't public.

**Comment by senagbe** [comment]
@dohaivu please implement this to make Szabolcs' rigourous testing and reporting easier.

**Comment by vsabolc** [comment]
Installed the app from GooglePlay - version 0.9.16 - Updated on 02/22/2018 and still cannot make screenshots - getting the same error.

**Comment by vsabolc** [comment]
Installed mainnetDebug-0.9.16.apk. With that  version of the app, screenshots could be made.

**Comment by dohaivu** [comment]
Yes, because I uploaded the release build to Play Store, not debug build :)
