### ISSUE TITLE
Android : Store transaction history and balance locally

### ISSUE THREAD

**Issue by dohaivu** [HTMLCOIN/htmlcoin-android#9]
Currently client does not store any data locally, so it's empty each time open it.
The app already stored contract locally, it's needed to extend to store history and balance

**Comment by dohaivu** [comment]
Realm database is implemented on Android.
Client will load data in local first

**Comment by vsabolc** [comment]
Killed the app and after killed the internet connections as well. Started the app and logged in - Store transaction and balance was displayed - OK.
