### ISSUE TITLE
Android: If the Wallet screen is refresh with the dark theme, Unconfirmed Balance section appears

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/htmlcoin-android#91]
@senagbe

Steps to reproduce:
- Open the Android app
- Log in
- Refresh the screen
- Only the Available Balance is visible
- Change the theme
- Refresh the Wallet screen
- Unconfirmed Balance has appeared as well

![unconfirmed](https://user-images.githubusercontent.com/4669689/38611014-e05b88c8-3d82-11e8-9735-81630522b92f.png)

**Comment by senagbe** [comment]
@longpham2310 dark theme should be disabled.

**Comment by dohaivu** [comment]
Disabled dark theme

**Comment by vsabolc** [comment]
It is disabled. Cannot reproduce.
